### ISSUE TITLE
Cannot read properties of undefined (reading 'Z_SYNC_FLUSH')

### ISSUE THREAD

**Issue by octave** [klaviyo/klaviyo-api-node#37]
Added the latest `6.0.0` version to my Hydrogen/Remix project. And I can't even start my app:

```
TypeError: Cannot read properties of undefined (reading 'Z_SYNC_FLUSH')
    at node_modules/axios/dist/node/axios.cjs (/node_modules/axios/lib/adapters/http.js:29:25)
    at node_modules/klaviyo-api/dist/api/accountsApi.js (/node_modules/klaviyo-api/api/accountsApi.ts:13:1)
```

**Comment by Ian-Montgomery-Klaviyo** [comment]
Looks like this is an error with axios. I changed the way axios is imported in today's 6.0.1 release as a potential fix that was outlined in [this axios issue](https://github.com/axios/axios/issues/5011). Let us know if fix works or we need to connect farther to find a working solution.

**Comment by octave** [comment]
Thanks for your quick reply! I just tried with `6.0.1` and same error. 

In the meantime I switched to using the api with `fetch` which works fine.

**Comment by umxr** [comment]
@octave how did you manage to switch to using fetch? im running into the exact same issue
